service: aws-node-http-api-project
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1

  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:*
        - translate:*
      Resource: "*"
	
functions:
  - ${file(./src/routes/index.yml)}
  - ${file(./src/routes/persona.yml)}
  - ${file(./src/routes/swapi.yml)}

resources:
  Resources:
    PersonasTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: PersonasTable
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        
plugins:
  - serverless-offline
  - serverless-auto-swagger

custom:
  autoswagger:
    typefiles: ['./src/types/Persona.d.ts']

  
