service: aws-node-http-api-project
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-2

  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:*
      Resource:
        - "Fn::GetAtt": [PlanetasTable, Arn]
        - "Fn::GetAtt": [PersonasTable, Arn]
	
functions:
  - ${file(./src/routes/index.yml)}
  - ${file(./src/routes/persona.yml)}
  - ${file(./src/routes/planeta.yml)}

resources:
  Resources:
  
    PersonasTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: PersonasTable
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST

    PlanetasTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: PlanetasTable
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH  
        BillingMode: PAY_PER_REQUEST

  
