// this file was generated by serverless-auto-swagger
            module.exports = {
  "swagger": "2.0",
  "info": {
    "title": "aws-node-http-api-project",
    "version": "1"
  },
  "paths": {
    "/": {
      "get": {
        "summary": "home",
        "description": "",
        "operationId": "home.get./",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    },
    "/persona": {
      "get": {
        "summary": "personaIndex",
        "description": "",
        "operationId": "personaIndex.get./persona",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      },
      "post": {
        "summary": "personaCreate",
        "description": "",
        "operationId": "personaCreate.post./persona",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "in": "body",
            "name": "body",
            "description": "Body required in the request",
            "required": true,
            "schema": {
              "$ref": "#/definitions/Persona"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    },
    "/persona/{id}": {
      "get": {
        "summary": "personaShow",
        "description": "",
        "operationId": "personaShow.get./persona/{id}",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      },
      "put": {
        "summary": "personaUpdate",
        "description": "",
        "operationId": "personaUpdate.put./persona/{id}",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "in": "body",
            "name": "body",
            "description": "Body required in the request",
            "required": true,
            "schema": {
              "$ref": "#/definitions/Persona"
            }
          },
          {
            "name": "id",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      },
      "delete": {
        "summary": "personaRemove",
        "description": "",
        "operationId": "personaRemove.delete./persona/{id}",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    },
    "/swapi": {
      "get": {
        "summary": "swapiIndex",
        "description": "",
        "operationId": "swapiIndex.get./swapi",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    },
    "/swapi/{model}": {
      "get": {
        "summary": "swapiModel",
        "description": "",
        "operationId": "swapiModel.get./swapi/{model}",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "model",
            "in": "path",
            "required": true,
            "type": "string"
          },
          {
            "in": "query",
            "name": "page",
            "type": "integer",
            "description": "numero de la paginacion",
            "required": false
          }
        ],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    },
    "/swapi/{model}/{id}": {
      "get": {
        "summary": "swapiShow",
        "description": "",
        "operationId": "swapiShow.get./swapi/{model}/{id}",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "model",
            "in": "path",
            "required": true,
            "type": "string"
          },
          {
            "name": "id",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    }
  },
  "definitions": {
    "Persona": {
      "properties": {
        "nombre": {
          "title": "Persona.nombre",
          "type": "string"
        },
        "altura": {
          "title": "Persona.altura",
          "type": "number"
        },
        "peso": {
          "title": "Persona.peso",
          "type": "number"
        },
        "cabello_color": {
          "title": "Persona.cabello_color",
          "type": "string"
        },
        "piel_color": {
          "title": "Persona.piel_color",
          "type": "string"
        },
        "ojos_color": {
          "title": "Persona.ojos_color",
          "type": "string"
        },
        "ano_nacimiento": {
          "title": "Persona.ano_nacimiento",
          "type": "number"
        },
        "genero": {
          "title": "Persona.genero",
          "type": "string"
        },
        "planeta_natal": {
          "title": "Persona.planeta_natal",
          "type": "string"
        },
        "peliculas": {
          "items": {
            "title": "Persona.peliculas.[]",
            "type": "number"
          },
          "title": "Persona.peliculas",
          "type": "array"
        },
        "especies": {
          "items": {
            "title": "Persona.especies.[]",
            "type": "string"
          },
          "title": "Persona.especies",
          "type": "array"
        },
        "vehiculos": {
          "items": {
            "title": "Persona.vehiculos.[]",
            "type": "string"
          },
          "title": "Persona.vehiculos",
          "type": "array"
        },
        "naves_estelares": {
          "items": {
            "title": "Persona.naves_estelares.[]",
            "type": "string"
          },
          "title": "Persona.naves_estelares",
          "type": "array"
        },
        "link": {
          "title": "Persona.link",
          "type": "string"
        }
      },
      "required": [
        "nombre",
        "altura",
        "peso",
        "cabello_color",
        "piel_color",
        "ojos_color",
        "ano_nacimiento",
        "genero",
        "planeta_natal",
        "peliculas",
        "especies",
        "vehiculos",
        "naves_estelares",
        "link"
      ],
      "additionalProperties": false,
      "title": "Persona",
      "type": "object"
    }
  },
  "securityDefinitions": {}
};